# Plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload config %{
   set-option global plug_always_ensure true
}

plug "alexherbo2/kakoune-dracula-theme" theme

plug "alexherbo2/connect.kak" config %{
    require-module connect-fzf
}
plug "alexherbo2/explore.kak" config %{
    alias global explore-files fzf-files
    alias global explore-buffers fzf-buffers
    alias global f fzf-files
}

plug "alexherbo2/auto-pairs.kak" config %{
    hook global WinSetOption filetype=(rust|go) %{
        auto-pairs-enable
    }

    hook global WinSetOption filetype=rust %{
        set-option buffer auto_pairs ( ) { } [ ] \" \" ` `
    }
}

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 4
} config %{
    hook global WinSetOption filetype=(rust|kak) expandtab
}

plug "occivink/kakoune-sudo-write"

plug "occivink/kakoune-gdb" config %{
    decl str gdb_program "rust-gdb"

    hook global GlobalSetOption gdb_started=true %{
        map global normal <F5>    ': gdb-toggle-breakpoint<ret>'
        map global normal <F6>    ': gdb-print<ret>'
        map global normal <F7>    ': gdb-next<ret>'
        map global normal <F8>    ': gdb-step<ret>'
        map global normal <F9>    ': gdb-continue<ret>'
        map global normal <s-F12> ': gdb-finish<ret>'
    }

    hook global GlobalSetOption gdb_started=false %{
        unmap global normal <F5>    ': gdb-toggle-breakpoint<ret>'
        unmap global normal <F6>    ': gdb-print<ret>'
        unmap global normal <F7>    ': gdb-next<ret>'
        unmap global normal <F8>    ': gdb-step<ret>'
        unmap global normal <F9>    ': gdb-continue<ret>'
        unmap global normal <s-F12> ': gdb-finish<ret>'
    }
}

# plug "ul/kak-lsp" do %{
#     cargo install --locked --force --path .
# } config %{
#     # Debug LSP
#     set global lsp_cmd "kak-lsp --config %val{config}/configs/kak-lsp/kak-lsp.toml -s %val{session} -vvv --log /tmp/kak-lsp.log"
#     #set global lsp_cmd "kak-lsp --config %val{config}/configs/kak-lsp/kak-lsp.toml -s %val{session}"

#     hook global WinSetOption filetype=(rust|go) %{
#         lsp-enable-window
#     }

#     hook global WinSetOption filetype=rust %{
#         set buffer formatcmd 'rustfmt'
#         hook window BufWritePre .* lsp-formatting-sync

#         lsp-auto-signature-help-enable
#     }
# }

plug "https://gitlab.com/Screwtapello/kakoune-cargo"

# Config

## Style
colorscheme dracula

add-highlighter global/ number-lines

## Editor Settings
hook global InsertCompletionShow .* %{
    try %{
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

## Language Specifics
hook global WinSetOption filetype=rust %{
    set buffer formatcmd 'rustfmt'
}
