snippet_support = true
verbosity = 2

[semantic_scopes]
variable="variable"
entity_name_function="function"
entity_name_type="type"
variable_other_enummember="variable"
entity_name_namespace="module"

[server]
timeout = 15

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
#command = "ra_lsp_server"
command = "rls"

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", "go.mod"]
command = "gopls"
offset_encoding = "utf-8"
